/**
 * Auto-generated execution implementation for MOD_NAME ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_runtime/MOD_NAME/MOD_NAME_runtime.h"
#include "clio_runtime/MOD_NAME/autogen/MOD_NAME_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::run::MOD_NAME {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

chi::TaskResume Runtime::Run(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task, rctx));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task, rctx));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<MonitorTask> typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task, rctx));
      break;
    }
    case Method::kCustom: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CustomTask> typed_task = task_ptr.template Cast<CustomTask>();
      CLIO_CO_AWAIT(Custom(typed_task, rctx));
      break;
    }
    case Method::kCoMutexTest: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CoMutexTestTask> typed_task = task_ptr.template Cast<CoMutexTestTask>();
      CLIO_CO_AWAIT(CoMutexTest(typed_task, rctx));
      break;
    }
    case Method::kCoRwLockTest: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CoRwLockTestTask> typed_task = task_ptr.template Cast<CoRwLockTestTask>();
      CLIO_CO_AWAIT(CoRwLockTest(typed_task, rctx));
      break;
    }
    case Method::kWaitTest: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<WaitTestTask> typed_task = task_ptr.template Cast<WaitTestTask>();
      CLIO_CO_AWAIT(WaitTest(typed_task, rctx));
      break;
    }
    case Method::kTestLargeOutput: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<TestLargeOutputTask> typed_task = task_ptr.template Cast<TestLargeOutputTask>();
      CLIO_CO_AWAIT(TestLargeOutput(typed_task, rctx));
      break;
    }
    case Method::kGpuSubmit: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GpuSubmitTask> typed_task = task_ptr.template Cast<GpuSubmitTask>();
      CLIO_CO_AWAIT(GpuSubmit(typed_task, rctx));
      break;
    }
    case Method::kSubtaskTest: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<SubtaskTestTask> typed_task = task_ptr.template Cast<SubtaskTestTask>();
      co_await SubtaskTest(typed_task, rctx);
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.template Cast<CustomTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.template Cast<CoMutexTestTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.template Cast<CoRwLockTestTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.template Cast<WaitTestTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kTestLargeOutput: {
      auto typed_task = task_ptr.template Cast<TestLargeOutputTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGpuSubmit: {
      auto typed_task = task_ptr.template Cast<GpuSubmitTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSubtaskTest: {
      auto typed_task = task_ptr.template Cast<SubtaskTestTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.template Cast<CustomTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.template Cast<CoMutexTestTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.template Cast<CoRwLockTestTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.template Cast<WaitTestTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kTestLargeOutput: {
      auto typed_task = task_ptr.template Cast<TestLargeOutputTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGpuSubmit: {
      auto typed_task = task_ptr.template Cast<GpuSubmitTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSubtaskTest: {
      auto typed_task = task_ptr.template Cast<SubtaskTestTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  ctp::ipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive,
                            ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.template Cast<CustomTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.template Cast<CoMutexTestTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.template Cast<CoRwLockTestTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.template Cast<WaitTestTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kTestLargeOutput: {
      auto typed_task = task_ptr.template Cast<TestLargeOutputTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGpuSubmit: {
      auto typed_task = task_ptr.template Cast<GpuSubmitTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSubtaskTest: {
      auto typed_task = task_ptr.template Cast<SubtaskTestTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive) {
  ctp::ipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::DefaultSaveArchive& archive, 
                             ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCustom: {
      auto typed_task = task_ptr.template Cast<CustomTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = task_ptr.template Cast<CoMutexTestTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = task_ptr.template Cast<CoRwLockTestTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = task_ptr.template Cast<WaitTestTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kTestLargeOutput: {
      auto typed_task = task_ptr.template Cast<TestLargeOutputTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGpuSubmit: {
      auto typed_task = task_ptr.template Cast<GpuSubmitTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSubtaskTest: {
      auto typed_task = task_ptr.template Cast<SubtaskTestTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kCustom: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CustomTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CustomTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kCoMutexTest: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CoMutexTestTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CoMutexTestTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kCoRwLockTest: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CoRwLockTestTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CoRwLockTestTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWaitTest: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<WaitTestTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<WaitTestTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kTestLargeOutput: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<TestLargeOutputTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<TestLargeOutputTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGpuSubmit: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GpuSubmitTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GpuSubmitTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSubtaskTest: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SubtaskTestTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<SubtaskTestTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return ctp::ipc::FullPtr<chi::Task>();
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kCustom: {
      auto new_task_ptr = ipc_manager->NewTask<CustomTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kCoMutexTest: {
      auto new_task_ptr = ipc_manager->NewTask<CoMutexTestTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kCoRwLockTest: {
      auto new_task_ptr = ipc_manager->NewTask<CoRwLockTestTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kWaitTest: {
      auto new_task_ptr = ipc_manager->NewTask<WaitTestTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kTestLargeOutput: {
      auto new_task_ptr = ipc_manager->NewTask<TestLargeOutputTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGpuSubmit: {
      auto new_task_ptr = ipc_manager->NewTask<GpuSubmitTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSubtaskTest: {
      auto new_task_ptr = ipc_manager->NewTask<SubtaskTestTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return ctp::ipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task,
                        const ctp::ipc::FullPtr<chi::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = orig_task.template Cast<CreateTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kMonitor: {
      auto typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kCustom: {
      auto typed_task = orig_task.template Cast<CustomTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kCoMutexTest: {
      auto typed_task = orig_task.template Cast<CoMutexTestTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kCoRwLockTest: {
      auto typed_task = orig_task.template Cast<CoRwLockTestTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kWaitTest: {
      auto typed_task = orig_task.template Cast<WaitTestTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kTestLargeOutput: {
      auto typed_task = orig_task.template Cast<TestLargeOutputTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGpuSubmit: {
      auto typed_task = orig_task.template Cast<GpuSubmitTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed_task = orig_task.template Cast<SubtaskTestTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    default: {
      orig_task->Aggregate(replica_task);
      break;
    }
  }
}

void Runtime::DelTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kCustom: {
      ipc_manager->DelTask(task_ptr.template Cast<CustomTask>());
      break;
    }
    case Method::kCoMutexTest: {
      ipc_manager->DelTask(task_ptr.template Cast<CoMutexTestTask>());
      break;
    }
    case Method::kCoRwLockTest: {
      ipc_manager->DelTask(task_ptr.template Cast<CoRwLockTestTask>());
      break;
    }
    case Method::kWaitTest: {
      ipc_manager->DelTask(task_ptr.template Cast<WaitTestTask>());
      break;
    }
    case Method::kTestLargeOutput: {
      ipc_manager->DelTask(task_ptr.template Cast<TestLargeOutputTask>());
      break;
    }
    case Method::kGpuSubmit: {
      ipc_manager->DelTask(task_ptr.template Cast<GpuSubmitTask>());
      break;
    }
    case Method::kSubtaskTest: {
      ipc_manager->DelTask(task_ptr.template Cast<SubtaskTestTask>());
      break;
    }
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

} // namespace clio::run::MOD_NAME
