/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_cae/core/core_runtime.h"
#include "clio_cae/core/autogen/core_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::cae::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

chi::TaskResume Runtime::Run(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task, rctx));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task, rctx));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<MonitorTask> typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task, rctx));
      break;
    }
    case Method::kParseOmni: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<ParseOmniTask> typed_task = task_ptr.template Cast<ParseOmniTask>();
      CLIO_CO_AWAIT(ParseOmni(typed_task, rctx));
      break;
    }
    case Method::kProcessHdf5Dataset: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<ProcessHdf5DatasetTask> typed_task = task_ptr.template Cast<ProcessHdf5DatasetTask>();
      CLIO_CO_AWAIT(ProcessHdf5Dataset(typed_task, rctx));
      break;
    }
    case Method::kExportData: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<ExportDataTask> typed_task = task_ptr.template Cast<ExportDataTask>();
      CLIO_CO_AWAIT(ExportData(typed_task, rctx));
      break;
    }
    case Method::kPutBlob: {
      ctp::ipc::FullPtr<PutBlobTask> typed_task = task_ptr.template Cast<PutBlobTask>();
      CLIO_CO_AWAIT(PutBlob(typed_task, rctx));
      break;
    }
    case Method::kGetBlob: {
      ctp::ipc::FullPtr<GetBlobTask> typed_task = task_ptr.template Cast<GetBlobTask>();
      CLIO_CO_AWAIT(GetBlob(typed_task, rctx));
      break;
    }
    case Method::kGetOrCreateTag: {
      ctp::ipc::FullPtr<GetOrCreateTagTask> typed_task = task_ptr.template Cast<GetOrCreateTagTask>();
      CLIO_CO_AWAIT(GetOrCreateTag(typed_task, rctx));
      break;
    }
    case Method::kSemanticSearch: {
      ctp::ipc::FullPtr<SemanticSearchTask> typed_task = task_ptr.template Cast<SemanticSearchTask>();
      CLIO_CO_AWAIT(SemanticSearch(typed_task, rctx));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kParseOmni: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ParseOmniTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kProcessHdf5Dataset: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ProcessHdf5DatasetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ProcessHdf5DatasetTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kExportData: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ExportDataTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ExportDataTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<PutBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<GetBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<GetOrCreateTagTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<GetOrCreateTagTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSemanticSearch: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticSearchTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<SemanticSearchTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return ctp::ipc::FullPtr<chi::Task>();
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kParseOmni: {
      auto new_task_ptr = ipc_manager->NewTask<ParseOmniTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kProcessHdf5Dataset: {
      auto new_task_ptr = ipc_manager->NewTask<ProcessHdf5DatasetTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kExportData: {
      auto new_task_ptr = ipc_manager->NewTask<ExportDataTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<GetOrCreateTagTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSemanticSearch: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticSearchTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return ctp::ipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::DelTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kParseOmni: {
      ipc_manager->DelTask(task_ptr.template Cast<ParseOmniTask>());
      break;
    }
    case Method::kProcessHdf5Dataset: {
      ipc_manager->DelTask(task_ptr.template Cast<ProcessHdf5DatasetTask>());
      break;
    }
    case Method::kExportData: {
      ipc_manager->DelTask(task_ptr.template Cast<ExportDataTask>());
      break;
    }
    case Method::kPutBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<PutBlobTask>());
      break;
    }
    case Method::kGetBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobTask>());
      break;
    }
    case Method::kGetOrCreateTag: {
      ipc_manager->DelTask(task_ptr.template Cast<GetOrCreateTagTask>());
      break;
    }
    case Method::kSemanticSearch: {
      ipc_manager->DelTask(task_ptr.template Cast<SemanticSearchTask>());
      break;
    }
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

} // namespace clio::cae::core
