/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CLIO_CTE_ADAPTER_STDIO_NATIVE_H_
#define CLIO_CTE_ADAPTER_STDIO_NATIVE_H_

#include <memory>

#include "adapter/filesystem/filesystem.h"
#include "adapter/filesystem/filesystem_mdm.h"
#include "adapter/posix/posix_fs_api.h"
#include "stdio_api.h"
#include "clio_cte/core/content_transfer_engine.h"

namespace clio::cae {

/** A class to represent POSIX IO file system */
class StdioFs : public clio::cae::Filesystem {
public:
  CLIO_CTE_STDIO_API_T real_api_; /**< pointer to real APIs */

public:
  StdioFs() : Filesystem(AdapterType::kStdio) { real_api_ = CLIO_CTE_STDIO_API; }

  /** Close an existing stream and then open with new path */
  FILE *Reopen(const std::string &user_path, const char *mode,
               AdapterStat &stat) {
    auto real_api_ = CLIO_CTE_STDIO_API;
    FILE *ret;
    ret = real_api_->freopen(user_path.c_str(), mode, stat.fh_);
    if (!ret) {
      return ret;
    }
    stat.fh_ = ret;
    HLOG(kDebug, "Reopen file for filename: {} in mode {}", user_path, mode);
    stat.UpdateTime();
    return (FILE *)&stat;
  }

  /** fdopen */
  FILE *FdOpen(const std::string &mode, std::shared_ptr<AdapterStat> &stat) {
    auto real_api_ = CLIO_CTE_STDIO_API;
    auto mdm = CLIO_CTE_FS_METADATA_MANAGER;
    stat->fh_ = real_api_->fdopen(stat->fd_, mode.c_str());
    stat->mode_str_ = mode;
    File f;
    f.hermes_fh_ = (FILE *)stat.get();
    mdm->Create(f, stat);
    return f.hermes_fh_;
  }

  /** Whether or not \a fd FILE DESCRIPTOR is tracked */
  static bool IsFdTracked(int fd, std::shared_ptr<AdapterStat> &stat) {
    return PosixFs::IsFdTracked(fd, stat);
  }

  /** Whether or not \a fd FILE DESCRIPTOR is tracked */
  static bool IsFdTracked(int fd) { return PosixFs::IsFdTracked(fd); }

  /**
   * Whether \a fp was handed out by CTE.
   *
   * fopen()-returned FILE* pointers for clio:: paths land in our MDM;
   * everything else is foreign and we pass through.
   */
  static bool IsFpTracked(FILE *fp, std::shared_ptr<AdapterStat> &stat) {
    if (!fp) {
      return false;
    }
    // `HERMES` was a leftover macro from the Clio-era of this code;
    // the equivalent gate now is CTE_MANAGER's init flag.
    auto *cte_manager = CTE_MANAGER;
    if (cte_manager != nullptr && !cte_manager->IsInitialized()) {
      return false;
    }
    clio::cae::File f;
    f.hermes_fh_ = fp;
    stat = CLIO_CTE_FS_METADATA_MANAGER->Find(f);
    return stat != nullptr;
  }

  /** Whether or not \a fp FILE was generated by Clio */
  static bool IsFpTracked(FILE *fp) {
    std::shared_ptr<AdapterStat> stat;
    return IsFpTracked(fp, stat);
  }

  /** get the file name from \a fp file pointer */
  static std::string GetFilenameFromFP(FILE *fp) {
    char proclnk[kMaxPathLen];
    char filename[kMaxPathLen];
    int fno = fileno(fp);
    snprintf(proclnk, kMaxPathLen, "/proc/self/fd/%d", fno);
    size_t r = readlink(proclnk, filename, kMaxPathLen);
    filename[r] = '\0';
    return filename;
  }

public:
  /** Allocate an fd for the file f */
  void RealOpen(File &f, AdapterStat &stat, const std::string &path) override {
    if (stat.mode_str_.find('w') != std::string::npos) {
      stat.hflags_.SetBits(CLIO_CTE_FS_TRUNC);
      stat.hflags_.SetBits(CLIO_CTE_FS_CREATE);
    }
    if (stat.mode_str_.find('a') != std::string::npos) {
      stat.hflags_.SetBits(CLIO_CTE_FS_APPEND);
      stat.hflags_.SetBits(CLIO_CTE_FS_CREATE);
    }
    if (stat.mode_str_.find('r') != std::string::npos) {
      stat.hflags_.SetBits(CLIO_CTE_FS_READ);
    }
    if (stat.mode_str_.find('w') != std::string::npos) {
      stat.hflags_.SetBits(CLIO_CTE_FS_WRITE);
    }
    if (stat.mode_str_.find('+') != std::string::npos) {
      stat.hflags_.SetBits(CLIO_CTE_FS_READ | CLIO_CTE_FS_WRITE);
    }

    if (stat.hflags_.Any(CLIO_CTE_FS_CREATE)) {
      if (stat.adapter_mode_ != AdapterMode::kScratch) {
        stat.fh_ = real_api_->fopen(path.c_str(), stat.mode_str_.c_str());
      }
    } else {
      stat.fh_ = real_api_->fopen(path.c_str(), stat.mode_str_.c_str());
    }

    if (stat.fh_ != nullptr) {
      stat.hflags_.SetBits(CLIO_CTE_FS_EXISTS);
    }
    if (stat.fh_ == nullptr && stat.adapter_mode_ != AdapterMode::kScratch) {
      f.status_ = false;
    }
  }

  /**
   * Called after real open. Allocates the Clio representation of
   * identifying file information, such as a clio file descriptor
   * and clio file handler. These are not the same as STDIO file
   * descriptor and STDIO file handler.
   * */
  void HermesOpen(File &f, const AdapterStat &stat,
                  FilesystemIoClientState &fs_mdm) override {
    f.hermes_fh_ = (FILE *)fs_mdm.stat_;
  }

  /** Synchronize \a file FILE f */
  int RealSync(const File &f, const AdapterStat &stat) override {
    (void)f;
    if (stat.adapter_mode_ == AdapterMode::kScratch && stat.fh_ == nullptr) {
      return 0;
    }
    return real_api_->fflush(stat.fh_);
  }

  /** Close \a file FILE f */
  int RealClose(const File &f, AdapterStat &stat) override {
    if (stat.adapter_mode_ == AdapterMode::kScratch && stat.fh_ == nullptr) {
      return 0;
    }
    return real_api_->fclose(stat.fh_);
  }

  /**
   * Called before RealClose. Releases information provisioned during
   * the allocation phase.
   * */
  void HermesClose(File &f, const AdapterStat &stat,
                   FilesystemIoClientState &fs_mdm) override {
    (void)f;
    (void)stat;
    (void)fs_mdm;
  }

  /** Remove \a file FILE f */
  int RealRemove(const std::string &path) override {
    return remove(path.c_str());
  }

  /** Get initial statistics from the backend.
   *
   * Base class moved from chi::string to std::string and from Blob to
   * raw void*+size; mirror those signatures here so the override is
   * picked up. */
  size_t GetBackendSize(const std::string &bkt_name) override {
    size_t true_size = 0;
    int fd = open(bkt_name.c_str(), O_RDONLY);
    if (fd < 0) {
      return 0;
    }
    struct stat buf;
    fstat(fd, &buf);
    true_size = buf.st_size;
    close(fd);

    HLOG(kDebug, "The size of the file {} on disk is {}", bkt_name, true_size);
    return true_size;
  }

  /** Write blob to backend */
  void WriteBlob(const std::string &bkt_name, const void *data, size_t size,
                 const FsIoOptions &opts, IoStatus &status) override {
    status.success_ = true;
    HLOG(kDebug,
          "Writing to file: {} offset: {} size: {}",
          bkt_name, opts.backend_off_, size);
    FILE *fh = real_api_->fopen(bkt_name.c_str(), "r+");
    if (fh == nullptr) {
      status.size_ = 0;
      status.success_ = false;
      return;
    }
    real_api_->fseek(fh, opts.backend_off_, SEEK_SET);
    status.size_ = real_api_->fwrite(data, sizeof(char), size, fh);
    if (status.size_ != size) {
      status.success_ = false;
    }
    real_api_->fclose(fh);
  }

  /** Read blob from the backend */
  void ReadBlob(const std::string &bkt_name, void *data, size_t size,
                const FsIoOptions &opts, IoStatus &status) override {
    status.success_ = true;
    HLOG(kDebug,
          "Reading from file: {} offset: {} size: {}",
          bkt_name, opts.backend_off_, size);
    FILE *fh = real_api_->fopen(bkt_name.c_str(), "r");
    if (fh == nullptr) {
      status.size_ = 0;
      status.success_ = false;
      return;
    }
    real_api_->fseek(fh, opts.backend_off_, SEEK_SET);
    status.size_ = real_api_->fread(data, sizeof(char), size, fh);
    if (status.size_ != size) {
      status.success_ = false;
    }
    real_api_->fclose(fh);
  }

  void UpdateIoStatus(const FsIoOptions &opts, IoStatus &status) override {
    (void)opts;
    (void)status;
  }
};

/** Simplify access to the stateless StdioFs Singleton */
#define CLIO_CTE_STDIO_FS                                                        \
  ctp::Singleton<::clio::cae::StdioFs>::GetInstance()
#define CLIO_CTE_STDIO_FS_T clio::cae::StdioFs *

} // namespace clio::cae

#endif // CLIO_CTE_ADAPTER_STDIO_NATIVE_H_
