/**
 * Auto-generated execution implementation for admin ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "chimaera/admin/admin_runtime.h"
#include "chimaera/admin/autogen/admin_methods.h"
#include <chimaera/chimaera.h>
#include <chimaera/task.h>  // For TaskResume coroutine return type

namespace chimaera::admin {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

chi::TaskResume Runtime::Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  CHI_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      CHI_CO_AWAIT(Create(typed_task, rctx));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      CHI_CO_AWAIT(Destroy(typed_task, rctx));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<MonitorTask> typed_task = task_ptr.template Cast<MonitorTask>();
      CHI_CO_AWAIT(Monitor(typed_task, rctx));
      break;
    }
    case Method::kGetOrCreatePool: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<admin::GetOrCreatePoolTask<admin::CreateParams>> typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      CHI_CO_AWAIT(GetOrCreatePool(typed_task, rctx));
      break;
    }
    case Method::kDestroyPool: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<DestroyPoolTask> typed_task = task_ptr.template Cast<DestroyPoolTask>();
      CHI_CO_AWAIT(DestroyPool(typed_task, rctx));
      break;
    }
    case Method::kStopRuntime: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<StopRuntimeTask> typed_task = task_ptr.template Cast<StopRuntimeTask>();
      CHI_CO_AWAIT(StopRuntime(typed_task, rctx));
      break;
    }
    case Method::kFlush: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<FlushTask> typed_task = task_ptr.template Cast<FlushTask>();
      CHI_CO_AWAIT(Flush(typed_task, rctx));
      break;
    }
    case Method::kSend: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<SendTask> typed_task = task_ptr.template Cast<SendTask>();
      CHI_CO_AWAIT(Send(typed_task, rctx));
      break;
    }
    case Method::kRecv: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RecvTask> typed_task = task_ptr.template Cast<RecvTask>();
      CHI_CO_AWAIT(Recv(typed_task, rctx));
      break;
    }
    case Method::kClientConnect: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ClientConnectTask> typed_task = task_ptr.template Cast<ClientConnectTask>();
      CHI_CO_AWAIT(ClientConnect(typed_task, rctx));
      break;
    }
    case Method::kSubmitBatch: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<SubmitBatchTask> typed_task = task_ptr.template Cast<SubmitBatchTask>();
      CHI_CO_AWAIT(SubmitBatch(typed_task, rctx));
      break;
    }
    case Method::kWreapDeadIpcs: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<WreapDeadIpcsTask> typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      CHI_CO_AWAIT(WreapDeadIpcs(typed_task, rctx));
      break;
    }
    case Method::kClientRecv: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ClientRecvTask> typed_task = task_ptr.template Cast<ClientRecvTask>();
      CHI_CO_AWAIT(ClientRecv(typed_task, rctx));
      break;
    }
    case Method::kClientSend: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ClientSendTask> typed_task = task_ptr.template Cast<ClientSendTask>();
      CHI_CO_AWAIT(ClientSend(typed_task, rctx));
      break;
    }
    case Method::kRegisterMemory: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RegisterMemoryTask> typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      CHI_CO_AWAIT(RegisterMemory(typed_task, rctx));
      break;
    }
    case Method::kRestartContainers: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RestartContainersTask> typed_task = task_ptr.template Cast<RestartContainersTask>();
      CHI_CO_AWAIT(RestartContainers(typed_task, rctx));
      break;
    }
    case Method::kAddNode: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<AddNodeTask> typed_task = task_ptr.template Cast<AddNodeTask>();
      CHI_CO_AWAIT(AddNode(typed_task, rctx));
      break;
    }
    case Method::kChangeAddressTable: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ChangeAddressTableTask> typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      CHI_CO_AWAIT(ChangeAddressTable(typed_task, rctx));
      break;
    }
    case Method::kMigrateContainers: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<MigrateContainersTask> typed_task = task_ptr.template Cast<MigrateContainersTask>();
      CHI_CO_AWAIT(MigrateContainers(typed_task, rctx));
      break;
    }
    case Method::kHeartbeat: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<HeartbeatTask> typed_task = task_ptr.template Cast<HeartbeatTask>();
      CHI_CO_AWAIT(Heartbeat(typed_task, rctx));
      break;
    }
    case Method::kHeartbeatProbe: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<HeartbeatProbeTask> typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      CHI_CO_AWAIT(HeartbeatProbe(typed_task, rctx));
      break;
    }
    case Method::kProbeRequest: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<ProbeRequestTask> typed_task = task_ptr.template Cast<ProbeRequestTask>();
      CHI_CO_AWAIT(ProbeRequest(typed_task, rctx));
      break;
    }
    case Method::kRecoverContainers: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RecoverContainersTask> typed_task = task_ptr.template Cast<RecoverContainersTask>();
      CHI_CO_AWAIT(RecoverContainers(typed_task, rctx));
      break;
    }
    case Method::kSystemMonitor: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<SystemMonitorTask> typed_task = task_ptr.template Cast<SystemMonitorTask>();
      CHI_CO_AWAIT(SystemMonitor(typed_task, rctx));
      break;
    }
    case Method::kAnnounceShutdown: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<AnnounceShutdownTask> typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      CHI_CO_AWAIT(AnnounceShutdown(typed_task, rctx));
      break;
    }
    case Method::kRegisterGpuContainer: {
      // Cast task FullPtr to specific type
      hipc::FullPtr<RegisterGpuContainerTask> typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      co_await RegisterGpuContainer(typed_task, rctx);
      break;
    }
    default: {
      // Placeholder for future benchmark task handling
      // Reserved for specialized task types
      break;
    }
  }
  CHI_CO_RETURN;
  CHI_TASK_BODY_END
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kClientConnect: {
      auto typed_task = task_ptr.template Cast<ClientConnectTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSubmitBatch: {
      auto typed_task = task_ptr.template Cast<SubmitBatchTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kClientRecv: {
      auto typed_task = task_ptr.template Cast<ClientRecvTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kClientSend: {
      auto typed_task = task_ptr.template Cast<ClientSendTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterMemory: {
      auto typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRestartContainers: {
      auto typed_task = task_ptr.template Cast<RestartContainersTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAddNode: {
      auto typed_task = task_ptr.template Cast<AddNodeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kChangeAddressTable: {
      auto typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMigrateContainers: {
      auto typed_task = task_ptr.template Cast<MigrateContainersTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeat: {
      auto typed_task = task_ptr.template Cast<HeartbeatTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kProbeRequest: {
      auto typed_task = task_ptr.template Cast<ProbeRequestTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecoverContainers: {
      auto typed_task = task_ptr.template Cast<RecoverContainersTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSystemMonitor: {
      auto typed_task = task_ptr.template Cast<SystemMonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kClientConnect: {
      auto typed_task = task_ptr.template Cast<ClientConnectTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSubmitBatch: {
      auto typed_task = task_ptr.template Cast<SubmitBatchTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kClientRecv: {
      auto typed_task = task_ptr.template Cast<ClientRecvTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kClientSend: {
      auto typed_task = task_ptr.template Cast<ClientSendTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterMemory: {
      auto typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRestartContainers: {
      auto typed_task = task_ptr.template Cast<RestartContainersTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAddNode: {
      auto typed_task = task_ptr.template Cast<AddNodeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kChangeAddressTable: {
      auto typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMigrateContainers: {
      auto typed_task = task_ptr.template Cast<MigrateContainersTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeat: {
      auto typed_task = task_ptr.template Cast<HeartbeatTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kProbeRequest: {
      auto typed_task = task_ptr.template Cast<ProbeRequestTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecoverContainers: {
      auto typed_task = task_ptr.template Cast<RecoverContainersTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSystemMonitor: {
      auto typed_task = task_ptr.template Cast<SystemMonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive,
                            hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kClientConnect: {
      auto typed_task = task_ptr.template Cast<ClientConnectTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSubmitBatch: {
      auto typed_task = task_ptr.template Cast<SubmitBatchTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kClientRecv: {
      auto typed_task = task_ptr.template Cast<ClientRecvTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kClientSend: {
      auto typed_task = task_ptr.template Cast<ClientSendTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterMemory: {
      auto typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRestartContainers: {
      auto typed_task = task_ptr.template Cast<RestartContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAddNode: {
      auto typed_task = task_ptr.template Cast<AddNodeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kChangeAddressTable: {
      auto typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMigrateContainers: {
      auto typed_task = task_ptr.template Cast<MigrateContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeat: {
      auto typed_task = task_ptr.template Cast<HeartbeatTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kProbeRequest: {
      auto typed_task = task_ptr.template Cast<ProbeRequestTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRecoverContainers: {
      auto typed_task = task_ptr.template Cast<RecoverContainersTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSystemMonitor: {
      auto typed_task = task_ptr.template Cast<SystemMonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive) {
  hipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::DefaultSaveArchive& archive, 
                             hipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = task_ptr.template Cast<DestroyPoolTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = task_ptr.template Cast<StopRuntimeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlush: {
      auto typed_task = task_ptr.template Cast<FlushTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSend: {
      auto typed_task = task_ptr.template Cast<SendTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecv: {
      auto typed_task = task_ptr.template Cast<RecvTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kClientConnect: {
      auto typed_task = task_ptr.template Cast<ClientConnectTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSubmitBatch: {
      auto typed_task = task_ptr.template Cast<SubmitBatchTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto typed_task = task_ptr.template Cast<WreapDeadIpcsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kClientRecv: {
      auto typed_task = task_ptr.template Cast<ClientRecvTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kClientSend: {
      auto typed_task = task_ptr.template Cast<ClientSendTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterMemory: {
      auto typed_task = task_ptr.template Cast<RegisterMemoryTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRestartContainers: {
      auto typed_task = task_ptr.template Cast<RestartContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAddNode: {
      auto typed_task = task_ptr.template Cast<AddNodeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kChangeAddressTable: {
      auto typed_task = task_ptr.template Cast<ChangeAddressTableTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMigrateContainers: {
      auto typed_task = task_ptr.template Cast<MigrateContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeat: {
      auto typed_task = task_ptr.template Cast<HeartbeatTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kHeartbeatProbe: {
      auto typed_task = task_ptr.template Cast<HeartbeatProbeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kProbeRequest: {
      auto typed_task = task_ptr.template Cast<ProbeRequestTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRecoverContainers: {
      auto typed_task = task_ptr.template Cast<RecoverContainersTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSystemMonitor: {
      auto typed_task = task_ptr.template Cast<SystemMonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kAnnounceShutdown: {
      auto typed_task = task_ptr.template Cast<AnnounceShutdownTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto typed_task = task_ptr.template Cast<RegisterGpuContainerTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

hipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, hipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreatePool: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroyPool: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyPoolTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStopRuntime: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<StopRuntimeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlush: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<FlushTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSend: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<SendTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRecv: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RecvTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kClientConnect: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ClientConnectTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ClientConnectTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSubmitBatch: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SubmitBatchTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<SubmitBatchTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kWreapDeadIpcs: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<WreapDeadIpcsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<WreapDeadIpcsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kClientRecv: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ClientRecvTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ClientRecvTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kClientSend: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ClientSendTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ClientSendTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRegisterMemory: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterMemoryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RegisterMemoryTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRestartContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RestartContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RestartContainersTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAddNode: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<AddNodeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<AddNodeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kChangeAddressTable: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ChangeAddressTableTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ChangeAddressTableTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMigrateContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MigrateContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MigrateContainersTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kHeartbeat: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<HeartbeatTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kHeartbeatProbe: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatProbeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<HeartbeatProbeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kProbeRequest: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ProbeRequestTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ProbeRequestTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRecoverContainers: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RecoverContainersTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RecoverContainersTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSystemMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<SystemMonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<SystemMonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kAnnounceShutdown: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<AnnounceShutdownTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<AnnounceShutdownTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRegisterGpuContainer: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterGpuContainerTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RegisterGpuContainerTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return hipc::FullPtr<chi::Task>();
}

hipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return hipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetOrCreatePool: {
      auto new_task_ptr = ipc_manager->NewTask<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroyPool: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyPoolTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kStopRuntime: {
      auto new_task_ptr = ipc_manager->NewTask<StopRuntimeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFlush: {
      auto new_task_ptr = ipc_manager->NewTask<FlushTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSend: {
      auto new_task_ptr = ipc_manager->NewTask<SendTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRecv: {
      auto new_task_ptr = ipc_manager->NewTask<RecvTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kClientConnect: {
      auto new_task_ptr = ipc_manager->NewTask<ClientConnectTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSubmitBatch: {
      auto new_task_ptr = ipc_manager->NewTask<SubmitBatchTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kWreapDeadIpcs: {
      auto new_task_ptr = ipc_manager->NewTask<WreapDeadIpcsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kClientRecv: {
      auto new_task_ptr = ipc_manager->NewTask<ClientRecvTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kClientSend: {
      auto new_task_ptr = ipc_manager->NewTask<ClientSendTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRegisterMemory: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterMemoryTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRestartContainers: {
      auto new_task_ptr = ipc_manager->NewTask<RestartContainersTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kAddNode: {
      auto new_task_ptr = ipc_manager->NewTask<AddNodeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kChangeAddressTable: {
      auto new_task_ptr = ipc_manager->NewTask<ChangeAddressTableTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMigrateContainers: {
      auto new_task_ptr = ipc_manager->NewTask<MigrateContainersTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kHeartbeat: {
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kHeartbeatProbe: {
      auto new_task_ptr = ipc_manager->NewTask<HeartbeatProbeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kProbeRequest: {
      auto new_task_ptr = ipc_manager->NewTask<ProbeRequestTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRecoverContainers: {
      auto new_task_ptr = ipc_manager->NewTask<RecoverContainersTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSystemMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<SystemMonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kAnnounceShutdown: {
      auto new_task_ptr = ipc_manager->NewTask<AnnounceShutdownTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRegisterGpuContainer: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterGpuContainerTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return hipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, hipc::FullPtr<chi::Task> orig_task,
                        const hipc::FullPtr<chi::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = orig_task.template Cast<CreateTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kMonitor: {
      auto typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetOrCreatePool: {
      auto typed_task = orig_task.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroyPool: {
      auto typed_task = orig_task.template Cast<DestroyPoolTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kStopRuntime: {
      auto typed_task = orig_task.template Cast<StopRuntimeTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kFlush: {
      auto typed_task = orig_task.template Cast<FlushTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kSend: {
      auto typed_task = orig_task.template Cast<SendTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRecv: {
      auto typed_task = orig_task.template Cast<RecvTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kClientConnect: {
      auto typed_task = orig_task.template Cast<ClientConnectTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kSubmitBatch: {
      auto typed_task = orig_task.template Cast<SubmitBatchTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kWreapDeadIpcs: {
      auto typed_task = orig_task.template Cast<WreapDeadIpcsTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kClientRecv: {
      auto typed_task = orig_task.template Cast<ClientRecvTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kClientSend: {
      auto typed_task = orig_task.template Cast<ClientSendTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRegisterMemory: {
      auto typed_task = orig_task.template Cast<RegisterMemoryTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRestartContainers: {
      auto typed_task = orig_task.template Cast<RestartContainersTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kAddNode: {
      auto typed_task = orig_task.template Cast<AddNodeTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kChangeAddressTable: {
      auto typed_task = orig_task.template Cast<ChangeAddressTableTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kMigrateContainers: {
      auto typed_task = orig_task.template Cast<MigrateContainersTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kHeartbeat: {
      auto typed_task = orig_task.template Cast<HeartbeatTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kHeartbeatProbe: {
      auto typed_task = orig_task.template Cast<HeartbeatProbeTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kProbeRequest: {
      auto typed_task = orig_task.template Cast<ProbeRequestTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRecoverContainers: {
      auto typed_task = orig_task.template Cast<RecoverContainersTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kSystemMonitor: {
      auto typed_task = orig_task.template Cast<SystemMonitorTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kAnnounceShutdown: {
      auto typed_task = orig_task.template Cast<AnnounceShutdownTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRegisterGpuContainer: {
      auto typed_task = orig_task.template Cast<RegisterGpuContainerTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    default: {
      orig_task->Aggregate(replica_task);
      break;
    }
  }
}

void Runtime::DelTask(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kGetOrCreatePool: {
      ipc_manager->DelTask(task_ptr.template Cast<admin::GetOrCreatePoolTask<admin::CreateParams>>());
      break;
    }
    case Method::kDestroyPool: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyPoolTask>());
      break;
    }
    case Method::kStopRuntime: {
      ipc_manager->DelTask(task_ptr.template Cast<StopRuntimeTask>());
      break;
    }
    case Method::kFlush: {
      ipc_manager->DelTask(task_ptr.template Cast<FlushTask>());
      break;
    }
    case Method::kSend: {
      ipc_manager->DelTask(task_ptr.template Cast<SendTask>());
      break;
    }
    case Method::kRecv: {
      ipc_manager->DelTask(task_ptr.template Cast<RecvTask>());
      break;
    }
    case Method::kClientConnect: {
      ipc_manager->DelTask(task_ptr.template Cast<ClientConnectTask>());
      break;
    }
    case Method::kSubmitBatch: {
      ipc_manager->DelTask(task_ptr.template Cast<SubmitBatchTask>());
      break;
    }
    case Method::kWreapDeadIpcs: {
      ipc_manager->DelTask(task_ptr.template Cast<WreapDeadIpcsTask>());
      break;
    }
    case Method::kClientRecv: {
      ipc_manager->DelTask(task_ptr.template Cast<ClientRecvTask>());
      break;
    }
    case Method::kClientSend: {
      ipc_manager->DelTask(task_ptr.template Cast<ClientSendTask>());
      break;
    }
    case Method::kRegisterMemory: {
      ipc_manager->DelTask(task_ptr.template Cast<RegisterMemoryTask>());
      break;
    }
    case Method::kRestartContainers: {
      ipc_manager->DelTask(task_ptr.template Cast<RestartContainersTask>());
      break;
    }
    case Method::kAddNode: {
      ipc_manager->DelTask(task_ptr.template Cast<AddNodeTask>());
      break;
    }
    case Method::kChangeAddressTable: {
      ipc_manager->DelTask(task_ptr.template Cast<ChangeAddressTableTask>());
      break;
    }
    case Method::kMigrateContainers: {
      ipc_manager->DelTask(task_ptr.template Cast<MigrateContainersTask>());
      break;
    }
    case Method::kHeartbeat: {
      ipc_manager->DelTask(task_ptr.template Cast<HeartbeatTask>());
      break;
    }
    case Method::kHeartbeatProbe: {
      ipc_manager->DelTask(task_ptr.template Cast<HeartbeatProbeTask>());
      break;
    }
    case Method::kProbeRequest: {
      ipc_manager->DelTask(task_ptr.template Cast<ProbeRequestTask>());
      break;
    }
    case Method::kRecoverContainers: {
      ipc_manager->DelTask(task_ptr.template Cast<RecoverContainersTask>());
      break;
    }
    case Method::kSystemMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<SystemMonitorTask>());
      break;
    }
    case Method::kAnnounceShutdown: {
      ipc_manager->DelTask(task_ptr.template Cast<AnnounceShutdownTask>());
      break;
    }
    case Method::kRegisterGpuContainer: {
      ipc_manager->DelTask(task_ptr.template Cast<RegisterGpuContainerTask>());
      break;
    }
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

} // namespace chimaera::admin
