/**
 * Auto-generated execution implementation for core ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "clio_cte/core/core_runtime.h"
#include "clio_cte/core/autogen/core_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace clio::cte::core {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

void Runtime::Restart(const chi::PoolId &pool_id, const std::string &pool_name,
                      chi::u32 container_id) {
  is_restart_ = true;
  Init(pool_id, pool_name, container_id);
}

chi::TaskResume Runtime::Run(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr, chi::RunContext& rctx) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<CreateTask> typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task, rctx));
      break;
    }
    case Method::kDestroy: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DestroyTask> typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task, rctx));
      break;
    }
    case Method::kMonitor: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<MonitorTask> typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task, rctx));
      break;
    }
    case Method::kRegisterTarget: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<RegisterTargetTask> typed_task = task_ptr.template Cast<RegisterTargetTask>();
      CLIO_CO_AWAIT(RegisterTarget(typed_task, rctx));
      break;
    }
    case Method::kUnregisterTarget: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<UnregisterTargetTask> typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      CLIO_CO_AWAIT(UnregisterTarget(typed_task, rctx));
      break;
    }
    case Method::kListTargets: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<ListTargetsTask> typed_task = task_ptr.template Cast<ListTargetsTask>();
      CLIO_CO_AWAIT(ListTargets(typed_task, rctx));
      break;
    }
    case Method::kStatTargets: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<StatTargetsTask> typed_task = task_ptr.template Cast<StatTargetsTask>();
      CLIO_CO_AWAIT(StatTargets(typed_task, rctx));
      break;
    }
    case Method::kGetOrCreateTag: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<core::GetOrCreateTagTask<core::CreateParams>> typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      CLIO_CO_AWAIT(GetOrCreateTag(typed_task, rctx));
      break;
    }
    case Method::kPutBlob: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<PutBlobTask> typed_task = task_ptr.template Cast<PutBlobTask>();
      CLIO_CO_AWAIT(PutBlob(typed_task, rctx));
      break;
    }
    case Method::kGetBlob: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetBlobTask> typed_task = task_ptr.template Cast<GetBlobTask>();
      CLIO_CO_AWAIT(GetBlob(typed_task, rctx));
      break;
    }
    case Method::kReorganizeBlob: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<ReorganizeBlobTask> typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      CLIO_CO_AWAIT(ReorganizeBlob(typed_task, rctx));
      break;
    }
    case Method::kDelBlob: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DelBlobTask> typed_task = task_ptr.template Cast<DelBlobTask>();
      CLIO_CO_AWAIT(DelBlob(typed_task, rctx));
      break;
    }
    case Method::kDelTag: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<DelTagTask> typed_task = task_ptr.template Cast<DelTagTask>();
      CLIO_CO_AWAIT(DelTag(typed_task, rctx));
      break;
    }
    case Method::kGetTagSize: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetTagSizeTask> typed_task = task_ptr.template Cast<GetTagSizeTask>();
      CLIO_CO_AWAIT(GetTagSize(typed_task, rctx));
      break;
    }
    case Method::kPollTelemetryLog: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<PollTelemetryLogTask> typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      CLIO_CO_AWAIT(PollTelemetryLog(typed_task, rctx));
      break;
    }
    case Method::kGetBlobScore: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetBlobScoreTask> typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      CLIO_CO_AWAIT(GetBlobScore(typed_task, rctx));
      break;
    }
    case Method::kGetBlobSize: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetBlobSizeTask> typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      CLIO_CO_AWAIT(GetBlobSize(typed_task, rctx));
      break;
    }
    case Method::kGetContainedBlobs: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetContainedBlobsTask> typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      CLIO_CO_AWAIT(GetContainedBlobs(typed_task, rctx));
      break;
    }
    case Method::kGetBlobInfo: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetBlobInfoTask> typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      CLIO_CO_AWAIT(GetBlobInfo(typed_task, rctx));
      break;
    }
    case Method::kTagQuery: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<TagQueryTask> typed_task = task_ptr.template Cast<TagQueryTask>();
      CLIO_CO_AWAIT(TagQuery(typed_task, rctx));
      break;
    }
    case Method::kBlobQuery: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<BlobQueryTask> typed_task = task_ptr.template Cast<BlobQueryTask>();
      CLIO_CO_AWAIT(BlobQuery(typed_task, rctx));
      break;
    }
    case Method::kGetTargetInfo: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<GetTargetInfoTask> typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      CLIO_CO_AWAIT(GetTargetInfo(typed_task, rctx));
      break;
    }
    case Method::kFlushMetadata: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<FlushMetadataTask> typed_task = task_ptr.template Cast<FlushMetadataTask>();
      CLIO_CO_AWAIT(FlushMetadata(typed_task, rctx));
      break;
    }
    case Method::kFlushData: {
      // Cast task FullPtr to specific type
      ctp::ipc::FullPtr<FlushDataTask> typed_task = task_ptr.template Cast<FlushDataTask>();
      CLIO_CO_AWAIT(FlushData(typed_task, rctx));
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      hipc::FullPtr<UpdateKnowledgeGraphTask> typed_task = task_ptr.template Cast<UpdateKnowledgeGraphTask>();
      co_await UpdateKnowledgeGraph(typed_task, rctx);
      break;
    }
    case Method::kSemanticQuery: {
      hipc::FullPtr<SemanticQueryTask> typed_task = task_ptr.template Cast<SemanticQueryTask>();
      co_await SemanticQuery(typed_task, rctx);
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      hipc::FullPtr<SyncKnowledgeGraphTask> typed_task = task_ptr.template Cast<SyncKnowledgeGraphTask>();
      co_await SyncKnowledgeGraph(typed_task, rctx);
      break;
    }
#endif
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlushMetadata: {
      auto typed_task = task_ptr.template Cast<FlushMetadataTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlushData: {
      auto typed_task = task_ptr.template Cast<FlushDataTask>();
      archive << *typed_task.ptr_;
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<UpdateKnowledgeGraphTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSemanticQuery: {
      auto typed_task = task_ptr.template Cast<SemanticQueryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<SyncKnowledgeGraphTask>();
      archive << *typed_task.ptr_;
      break;
    }
#endif
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive,
                        ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlushMetadata: {
      auto typed_task = task_ptr.template Cast<FlushMetadataTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlushData: {
      auto typed_task = task_ptr.template Cast<FlushDataTask>();
      archive >> *typed_task.ptr_;
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<UpdateKnowledgeGraphTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSemanticQuery: {
      auto typed_task = task_ptr.template Cast<SemanticQueryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<SyncKnowledgeGraphTask>();
      archive >> *typed_task.ptr_;
      break;
    }
#endif
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::AllocLoadTask(chi::u32 method, chi::LoadTaskArchive& archive) {
  ctp::ipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive,
                            ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlushMetadata: {
      auto typed_task = task_ptr.template Cast<FlushMetadataTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kFlushData: {
      auto typed_task = task_ptr.template Cast<FlushDataTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task.ptr_;
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<UpdateKnowledgeGraphTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSemanticQuery: {
      auto typed_task = task_ptr.template Cast<SemanticQueryTask>();
      archive >> *typed_task.ptr_;
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<SyncKnowledgeGraphTask>();
      archive >> *typed_task.ptr_;
      break;
    }
#endif
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::LocalAllocLoadTask(chi::u32 method, chi::DefaultLoadArchive& archive) {
  ctp::ipc::FullPtr<chi::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(chi::u32 method, chi::DefaultSaveArchive& archive, 
                             ctp::ipc::FullPtr<chi::Task> task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDestroy: {
      auto typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kMonitor: {
      auto typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = task_ptr.template Cast<RegisterTargetTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = task_ptr.template Cast<UnregisterTargetTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kListTargets: {
      auto typed_task = task_ptr.template Cast<ListTargetsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = task_ptr.template Cast<StatTargetsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = task_ptr.template Cast<PutBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = task_ptr.template Cast<GetBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = task_ptr.template Cast<ReorganizeBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = task_ptr.template Cast<DelBlobTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kDelTag: {
      auto typed_task = task_ptr.template Cast<DelTagTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = task_ptr.template Cast<GetTagSizeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = task_ptr.template Cast<PollTelemetryLogTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = task_ptr.template Cast<GetBlobScoreTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = task_ptr.template Cast<GetBlobSizeTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = task_ptr.template Cast<GetContainedBlobsTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed_task = task_ptr.template Cast<GetBlobInfoTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = task_ptr.template Cast<TagQueryTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = task_ptr.template Cast<BlobQueryTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed_task = task_ptr.template Cast<GetTargetInfoTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlushMetadata: {
      auto typed_task = task_ptr.template Cast<FlushMetadataTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kFlushData: {
      auto typed_task = task_ptr.template Cast<FlushDataTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task.ptr_;
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<UpdateKnowledgeGraphTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSemanticQuery: {
      auto typed_task = task_ptr.template Cast<SemanticQueryTask>();
      archive << *typed_task.ptr_;
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      auto typed_task = task_ptr.template Cast<SyncKnowledgeGraphTask>();
      archive << *typed_task.ptr_;
      break;
    }
#endif
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewCopyTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kRegisterTarget: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<RegisterTargetTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kUnregisterTarget: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<UnregisterTargetTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kListTargets: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ListTargetsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kStatTargets: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<StatTargetsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetOrCreateTag: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kPutBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<PutBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kReorganizeBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<ReorganizeBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDelBlob: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DelBlobTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kDelTag: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<DelTagTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetTagSize: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetTagSizeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kPollTelemetryLog: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<PollTelemetryLogTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlobScore: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobScoreTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlobSize: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobSizeTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetContainedBlobs: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetContainedBlobsTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetBlobInfo: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetBlobInfoTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetBlobInfoTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kTagQuery: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<TagQueryTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kBlobQuery: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<BlobQueryTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kGetTargetInfo: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<GetTargetInfoTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<GetTargetInfoTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlushMetadata: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushMetadataTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<FlushMetadataTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kFlushData: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<FlushDataTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto task_typed = orig_task_ptr.template Cast<FlushDataTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto new_task_ptr = ipc_manager->NewTask<UpdateKnowledgeGraphTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<UpdateKnowledgeGraphTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSemanticQuery: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticQueryTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<SemanticQueryTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      auto new_task_ptr = ipc_manager->NewTask<SyncKnowledgeGraphTask>();
      if (!new_task_ptr.IsNull()) {
        auto task_typed = orig_task_ptr.template Cast<SyncKnowledgeGraphTask>();
        new_task_ptr->Copy(task_typed);
        return new_task_ptr.template Cast<chi::Task>();
      }
      break;
    }
#endif
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_task_ptr);
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return ctp::ipc::FullPtr<chi::Task>();
}

ctp::ipc::FullPtr<chi::Task> Runtime::NewTask(chi::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return ctp::ipc::FullPtr<chi::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kRegisterTarget: {
      auto new_task_ptr = ipc_manager->NewTask<RegisterTargetTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kUnregisterTarget: {
      auto new_task_ptr = ipc_manager->NewTask<UnregisterTargetTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kListTargets: {
      auto new_task_ptr = ipc_manager->NewTask<ListTargetsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kStatTargets: {
      auto new_task_ptr = ipc_manager->NewTask<StatTargetsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetOrCreateTag: {
      auto new_task_ptr = ipc_manager->NewTask<core::GetOrCreateTagTask<core::CreateParams>>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kPutBlob: {
      auto new_task_ptr = ipc_manager->NewTask<PutBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlob: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kReorganizeBlob: {
      auto new_task_ptr = ipc_manager->NewTask<ReorganizeBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDelBlob: {
      auto new_task_ptr = ipc_manager->NewTask<DelBlobTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kDelTag: {
      auto new_task_ptr = ipc_manager->NewTask<DelTagTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetTagSize: {
      auto new_task_ptr = ipc_manager->NewTask<GetTagSizeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kPollTelemetryLog: {
      auto new_task_ptr = ipc_manager->NewTask<PollTelemetryLogTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlobScore: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobScoreTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlobSize: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobSizeTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetContainedBlobs: {
      auto new_task_ptr = ipc_manager->NewTask<GetContainedBlobsTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetBlobInfo: {
      auto new_task_ptr = ipc_manager->NewTask<GetBlobInfoTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kTagQuery: {
      auto new_task_ptr = ipc_manager->NewTask<TagQueryTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kBlobQuery: {
      auto new_task_ptr = ipc_manager->NewTask<BlobQueryTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kGetTargetInfo: {
      auto new_task_ptr = ipc_manager->NewTask<GetTargetInfoTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFlushMetadata: {
      auto new_task_ptr = ipc_manager->NewTask<FlushMetadataTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kFlushData: {
      auto new_task_ptr = ipc_manager->NewTask<FlushDataTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto new_task_ptr = ipc_manager->NewTask<UpdateKnowledgeGraphTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSemanticQuery: {
      auto new_task_ptr = ipc_manager->NewTask<SemanticQueryTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
    case Method::kSyncKnowledgeGraph: {
      auto new_task_ptr = ipc_manager->NewTask<SyncKnowledgeGraphTask>();
      return new_task_ptr.template Cast<chi::Task>();
    }
#endif
    default: {
      // For unknown methods, return null pointer
      return ctp::ipc::FullPtr<chi::Task>();
    }
  }
}

void Runtime::Aggregate(chi::u32 method, ctp::ipc::FullPtr<chi::Task> orig_task,
                        const ctp::ipc::FullPtr<chi::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto typed_task = orig_task.template Cast<CreateTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDestroy: {
      auto typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kMonitor: {
      auto typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kRegisterTarget: {
      auto typed_task = orig_task.template Cast<RegisterTargetTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed_task = orig_task.template Cast<UnregisterTargetTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kListTargets: {
      auto typed_task = orig_task.template Cast<ListTargetsTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kStatTargets: {
      auto typed_task = orig_task.template Cast<StatTargetsTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed_task = orig_task.template Cast<core::GetOrCreateTagTask<core::CreateParams>>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kPutBlob: {
      auto typed_task = orig_task.template Cast<PutBlobTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetBlob: {
      auto typed_task = orig_task.template Cast<GetBlobTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed_task = orig_task.template Cast<ReorganizeBlobTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDelBlob: {
      auto typed_task = orig_task.template Cast<DelBlobTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kDelTag: {
      auto typed_task = orig_task.template Cast<DelTagTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetTagSize: {
      auto typed_task = orig_task.template Cast<GetTagSizeTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed_task = orig_task.template Cast<PollTelemetryLogTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetBlobScore: {
      auto typed_task = orig_task.template Cast<GetBlobScoreTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetBlobSize: {
      auto typed_task = orig_task.template Cast<GetBlobSizeTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed_task = orig_task.template Cast<GetContainedBlobsTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed_task = orig_task.template Cast<GetBlobInfoTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kTagQuery: {
      auto typed_task = orig_task.template Cast<TagQueryTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kBlobQuery: {
      auto typed_task = orig_task.template Cast<BlobQueryTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed_task = orig_task.template Cast<GetTargetInfoTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kFlushMetadata: {
      auto typed_task = orig_task.template Cast<FlushMetadataTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kFlushData: {
      auto typed_task = orig_task.template Cast<FlushDataTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      auto typed_task = orig_task.template Cast<UpdateKnowledgeGraphTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kSemanticQuery: {
      auto typed_task = orig_task.template Cast<SemanticQueryTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      auto typed_task = orig_task.template Cast<SyncKnowledgeGraphTask>();
      typed_task->Aggregate(replica_task);
      break;
    }
#endif
    default: {
      orig_task->Aggregate(replica_task);
      break;
    }
  }
}

void Runtime::DelTask(chi::u32 method, ctp::ipc::FullPtr<chi::Task> task_ptr) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) return;
  switch (method) {
    case Method::kCreate: {
      ipc_manager->DelTask(task_ptr.template Cast<CreateTask>());
      break;
    }
    case Method::kDestroy: {
      ipc_manager->DelTask(task_ptr.template Cast<DestroyTask>());
      break;
    }
    case Method::kMonitor: {
      ipc_manager->DelTask(task_ptr.template Cast<MonitorTask>());
      break;
    }
    case Method::kRegisterTarget: {
      ipc_manager->DelTask(task_ptr.template Cast<RegisterTargetTask>());
      break;
    }
    case Method::kUnregisterTarget: {
      ipc_manager->DelTask(task_ptr.template Cast<UnregisterTargetTask>());
      break;
    }
    case Method::kListTargets: {
      ipc_manager->DelTask(task_ptr.template Cast<ListTargetsTask>());
      break;
    }
    case Method::kStatTargets: {
      ipc_manager->DelTask(task_ptr.template Cast<StatTargetsTask>());
      break;
    }
    case Method::kGetOrCreateTag: {
      ipc_manager->DelTask(task_ptr.template Cast<core::GetOrCreateTagTask<core::CreateParams>>());
      break;
    }
    case Method::kPutBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<PutBlobTask>());
      break;
    }
    case Method::kGetBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobTask>());
      break;
    }
    case Method::kReorganizeBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<ReorganizeBlobTask>());
      break;
    }
    case Method::kDelBlob: {
      ipc_manager->DelTask(task_ptr.template Cast<DelBlobTask>());
      break;
    }
    case Method::kDelTag: {
      ipc_manager->DelTask(task_ptr.template Cast<DelTagTask>());
      break;
    }
    case Method::kGetTagSize: {
      ipc_manager->DelTask(task_ptr.template Cast<GetTagSizeTask>());
      break;
    }
    case Method::kPollTelemetryLog: {
      ipc_manager->DelTask(task_ptr.template Cast<PollTelemetryLogTask>());
      break;
    }
    case Method::kGetBlobScore: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobScoreTask>());
      break;
    }
    case Method::kGetBlobSize: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobSizeTask>());
      break;
    }
    case Method::kGetContainedBlobs: {
      ipc_manager->DelTask(task_ptr.template Cast<GetContainedBlobsTask>());
      break;
    }
    case Method::kGetBlobInfo: {
      ipc_manager->DelTask(task_ptr.template Cast<GetBlobInfoTask>());
      break;
    }
    case Method::kTagQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<TagQueryTask>());
      break;
    }
    case Method::kBlobQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<BlobQueryTask>());
      break;
    }
    case Method::kGetTargetInfo: {
      ipc_manager->DelTask(task_ptr.template Cast<GetTargetInfoTask>());
      break;
    }
    case Method::kFlushMetadata: {
      ipc_manager->DelTask(task_ptr.template Cast<FlushMetadataTask>());
      break;
    }
    case Method::kFlushData: {
      ipc_manager->DelTask(task_ptr.template Cast<FlushDataTask>());
      break;
    }
#ifdef WRP_CTE_ENABLE_KNOWLEDGE_GRAPH
    case Method::kUpdateKnowledgeGraph: {
      ipc_manager->DelTask(task_ptr.template Cast<UpdateKnowledgeGraphTask>());
      break;
    }
    case Method::kSemanticQuery: {
      ipc_manager->DelTask(task_ptr.template Cast<SemanticQueryTask>());
      break;
    }
    case Method::kSyncKnowledgeGraph: {
      ipc_manager->DelTask(task_ptr.template Cast<SyncKnowledgeGraphTask>());
      break;
    }
#endif
    default: {
      ipc_manager->DelTask(task_ptr);
      break;
    }
  }
}

} // namespace clio::cte::core
